# Site settings
title: dvcoders
subtitle: Where coders belong
email: contact@dvcoders.com
description: dvcoders club website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dvcoders.com" # the base hostname & protocol for your site
twitter_username: dvcoders
github_username:  dvcoders
facebook_username: dvcoders
footer_note: dvcoders 2018
collections:
    - projects
exclude:
    - "_projects/template.markdown"

# Build settings
markdown: kramdown
