# Site settings
title: dvcoders
subtitle: Where the coders belong
email: info@dvcoders.com
description: DVCoders club website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dvcoders.github.io" # the base hostname & protocol for your site
twitter_username: dvcoders
github_username:  dvcoders
facebook_username: 
footer_note: dvcoders 2015
collections:
    - projects
exclude:
    - "_projects/template.markdown"

# Build settings
markdown: kramdown
