# Site settings
title: DVCoders
email: info@dvcoders.com
description: DVCoders official club website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dvcoders.github.io" # the base hostname & protocol for your site
twitter_username: dvcoders
github_username:  dvcoders

# Build settings
markdown: kramdown
